export const winText = [
    'Great Job!',
    'Well Done!',
    'Cool!',
    'Level Up.'
];

export const colorArrays = {
    "0": [{
        "background-color": "#FBC800",
        "border-color": "#997DFF"
    }, {
        "background-color": "#A3CA4F",
        "border-color": "#E27DFF"
    }, {
        "background-color": "#FF5A5A",
        "border-color": "#7FDAFB"
    }, {
        "background-color": "#24A1FF",
        "border-color": "#FFAF67"
    }, {
        "background-color": "#D590EA",
        "border-color": "#B3E059"
    }, {
        "background-color": "#47D7E8",
        "border-color": "#FF8383"
    }, {
        "background-color": "#3771FF",
        "border-color": "#FAC826"
    }, {
        "background-color": "#FA84AC",
        "border-color": "#68D893"
    }],
    "1": [{
        "background-color": "#5F35B8",
        "border-color": "#997DFF"
    }, {
        "background-color": "#AC10EB",
        "border-color": "#E27DFF"
    }, {
        "background-color": "#F133DB",
        "border-color": "#FAA3E9"
    }, {
        "background-color": "#FF5A5A",
        "border-color": "#FCA6BE"
    }, {
        "background-color": "#FF9440",
        "border-color": "#FCCC55"
    }, {
        "background-color": "#93C039",
        "border-color": "#B3E059"
    }, {
        "background-color": "#00B2E4",
        "border-color": "#72EDFB"
    }, {
        "background-color": "#3771FF",
        "border-color": "#5ABAFF"
    }],
    "2": [{
        "background-color": "#FEBC20",
        "border-color": "#FFEBB9"
    }, {
        "background-color": "#CF8ACD",
        "border-color": "#F7D0F6"
    }, {
        "background-color": "#CDDA2A",
        "border-color": "#F3F7B8"
    }, {
        "background-color": "#14D6C2",
        "border-color": "#9BEBE3"
    }, {
        "background-color": "#8F7ABD",
        "border-color": "#CBB9F1"
    }, {
        "background-color": "#3687BA",
        "border-color": "#62B1E1"
    }, {
        "background-color": "#1CA9FF",
        "border-color": "#98D8FF"
    }, {
        "background-color": "#FF9184",
        "border-color": "#FFC3BC"
    }],
    "3": [{
        "background-color": "#6A0000",
        "border-color": "#A14141"
    }, {
        "background-color": "#803802",
        "border-color": "#AA652F"
    }, {
        "background-color": "#926E06",
        "border-color": "#B18E29"
    }, {
        "background-color": "#8EA924",
        "border-color": "#BBCC7A"
    }, {
        "background-color": "#44948B",
        "border-color": "#7CC2BA"
    }, {
        "background-color": "#1087AB",
        "border-color": "#1BAFE9"
    }, {
        "background-color": "#0054C0",
        "border-color": "#4290F1"
    }, {
        "background-color": "#4101C8",
        "border-color": "#5A42F0"
    }, {
        "background-color": "#7100AC",
        "border-color": "#A44AD2"
    }]
};
