export const winText = [
    'Great Job!',
    'You\'re Amazing!',
    'Well Done!',
    'Cool!',
    'Level Up'
];

export const colorArrays = {
    "0": [{
        "background-color": "#6A0000",
        "border-color": "#390707"
    }, {
        "background-color": "#976803",
        "border-color": "#664212"
    }, {
        "background-color": "#9CA503",
        "border-color": "#718425"
    }, {
        "background-color": "#61A554",
        "border-color": "#2F871E"
    }, {
        "background-color": "#238C80",
        "border-color": "#076A5F"
    }, {
        "background-color": "#006FA4",
        "border-color": "#0F3660"
    }, {
        "background-color": "#4101C8",
        "border-color": "#440365"
    }, {
        "background-color": "#7100AC",
        "border-color": "#2A0B6E"
    }],    
    "1": [{
        "background-color": "#2910A9",
        "border-color": "#B19DFD"
    }, {
        "background-color": "#8604CD",
        "border-color": "#EDB8FC"
    }, {
        "background-color": "#D600CA",
        "border-color": "#FFC6F5"
    }, {
        "background-color": "#FF5A5A",
        "border-color": "#FFC7D7"
    }, {
        "background-color": "#FF9440",
        "border-color": "#FEE578"
    }, {
        "background-color": "#93C039",
        "border-color": "#CFF583"
    }, {
        "background-color": "#00A8E1",
        "border-color": "#97EFF9"
    }, {
        "background-color": "#3569E9",
        "border-color": "#68BFFD"
    }],
    "2": [{
        "background-color": "#F9A400",
        "border-color": "#FFEBB9"
    }, {
        "background-color": "#E176DE",
        "border-color": "#F7D0F6"
    }, {
        "background-color": "#BBCB00",
        "border-color": "#F3F7B8"
    }, {
        "background-color": "#9A74EB",
        "border-color": "#CBB9F1"
    }, {
        "background-color": "#14D6C2",
        "border-color": "#9BEBE3"
    }, {
        "background-color": "#0E7EC3",
        "border-color": "#62B1E1"
    }, {
        "background-color": "#1CA9FF",
        "border-color": "#98D8FF"
    }, {
        "background-color": "#FF7F7F",
        "border-color": "#FFC3BC"
    }],
    "3": [{
        "background-color": "#6A0000",
        "border-color": "#CD6464"
    }, {
        "background-color": "#976803",
        "border-color": "#D3AF4A"
    }, {
        "background-color": "#9CA503",
        "border-color": "#D7ED7F"
    }, {
        "background-color": "#61A554",
        "border-color": "#AFE0A6"
    }, {
        "background-color": "#238C80",
        "border-color": "#83E2D7"
    }, {
        "background-color": "#006FA4",
        "border-color": "#54CFFF"
    }, {
        "background-color": "#4101C8",
        "border-color": "#6990FF"
    }, {
        "background-color": "#7100AC",
        "border-color": "#B861E4"
    }],
    "4": [{
        "background-color": "#2910A9",
        "border-color": "#7055FF"
    }, {
        "background-color": "#8604CD",
        "border-color": "#BB3FFF"
    }, {
        "background-color": "#D600CA",
        "border-color": "#FF4AF5"
    }, {
        "background-color": "#FF5A5A",
        "border-color": "#FF9F4F"
    }, {
        "background-color": "#FF9440",
        "border-color": "#FFE200"
    }, {
        "background-color": "#93C039",
        "border-color": "#A7DF35"
    }, {
        "background-color": "#04AEC4",
        "border-color": "#3CD7E9"
    }, {
        "background-color": "#3569E9",
        "border-color": "#3FAFFF"
    }],
    "5": [{
        "background-color": "#F9A400",
        "border-color": "#FF9800"
    }, {
        "background-color": "#E176DE",
        "border-color": "#C35AC1"
    }, {
        "background-color": "#BBCB00",
        "border-color": "#A9AF62"
    }, {
        "background-color": "#9A74EB",
        "border-color": "#7D5FBF"
    }, {
        "background-color": "#14D6C2",
        "border-color": "#25BCAD"
    }, {
        "background-color": "#1DA9FF",
        "border-color": "#0B8EDE"
    }, {
        "background-color": "#0E7EC3",
        "border-color": "#0063BD"
    }, {
        "background-color": "#FF7F7F",
        "border-color": "#E66666"
    }]
};
